### ISSUE TITLE
Preprocess question

### ISSUE THREAD

**Issue by steven850** [OlaWod/FreeVC#33]
Your downsample.py creates 2 folders, 16khz and 22khz. Isnt the model only training on the 16khz data?

The preprocess_sr.py uses the 22k folder as its default, but why when wavlm is limited to 16khz?

Is there a purpose for this or just a default that you forgot to change? 
if I specify to use the 16khz folder, will this affect the preprocess or training any?

**Comment by OlaWod** [comment]
SR operation uses a vocoder. In this code, SR uses a 22kHz hifi-gan and then downsamples the resulted wav to 16kHz. You can also use a 16kHz vocoder to do this operation, such that the 22k folder is unnecessary. 
I chose 22kHz just because the publicly available [hifi-gan](https://github.com/jik876/hifi-gan) runs in 22kHz. (and many publicly available vocoders run in 22kHz too.) Just want to make it accessible to most people.
