### ISSUE TITLE
Question for commons.slice_segments(wav_padded, ids_slice * 480, wav_seglen)

### ISSUE THREAD

**Issue by lsw5835** [OlaWod/FreeVC#41]
Hi Thanks for great work and prompt feedback.

I am trying to finetune 24k model with custom dataset.
But when I try to make 'wav_padded' using 'commons'.slice_disclass(slice_disclass,ids_disclass * 480, wav_seglen), error occurred.
In the code, if the 'ids_slice * 480 + wav_seqlen' is longer than the length of 'wav_padded', an error occurs, so how can I solve this case?
The followings are error message. 

RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/hudson-4way/anaconda3/envs/freevc/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 302, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/hudson-4way/anaconda3/envs/freevc/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 61, in fetch
    return self.collate_fn(data)
  File "/home/hudson-4way/Voice/FreeVC/data_utils_24.py", line 198, in __call__
    wav_padded = commons.slice_segments(wav_padded, ids_slice * 480, wav_seglen)
  File "/home/hudson-4way/Voice/FreeVC/commons.py", line 54, in slice_segments
    ret[i] = x[i, :, idx_str:idx_end]
RuntimeError: The expanded size of the tensor (37440) must match the existing size (36983) at non-singleton dimension 1.  Target sizes: [1, 37440].  Tensor sizes: [36983]

**Comment by OlaWod** [comment]
This may be caused by data preprocessing, the audio length doesn't match spectrogram length.
`librosa.effects.trim` can have different trimed segment with different sampling rates. For example, `wav, _ = librosa.effects.trim(<24k_wav>, top_db=20)` might trim out the first 0.3 seconds, while `wav, _ = librosa.effects.trim(<22k_wav>, top_db=20)` might trim out the first 0.33 seconds.
The 24k wav and 16k spectrogram and 16k wavlm feature should be from the same segment.
And btw I just found that I forgot librosa loads 22k wav by default, the original downsampling code upsamples 22k wav to 24k wav. Just fixed [it](https://github.com/OlaWod/FreeVC/blob/3cf11de513d6e3336414c2b49479d614eba76777/tips-for-synthesizing-24KHz-wavs-from-16kHz-wavs/downsample_24k.py#L21).

**Comment by lsw5835** [comment]
Thanks for your kindly answering.
Then, if there is no leading and trailing silence, is there no difference in length between 16k spectrogram and 24k wav?

**Comment by OlaWod** [comment]
If you didn't trim both 16k wav (where the 16k spectrogram come from) and 24k wav, then yes.
`librosa.effects.trim` might have the possibility to trim a little even if there is no apparent leading and trailing silence.

**Comment by lsw5835** [comment]
Thanks very much. After matching the length of 16k and 24k it works fine.
