### ISSUE TITLE
s-o-p pronunciation , high-low tone distortion

### ISSUE THREAD

**Issue by lsw5835** [OlaWod/FreeVC#51]
Hi, Thank you for quick replies and kindness.

While testing through fine-tuning on various data, i found that distortion occurs in o, s, and p pronunciation in common, and distortion also occurs when generating high-pitched sounds rather than target speaker data. Is there a way to solve two problems?

Or, it would be very helpful if you could tell me the metric that can check the presence or absence of distortion.

Thanks very much.

**Comment by steven850** [comment]
I have Noticed the same, when a model is fine tuned to a specific speaker, the S sounds are really bad, so anything ending in S especially if its a longer S. I have only noticed it with S sounds though, I havent seen a problem with P or O. 

I think he meant the output is not that of the target speaker?

**Comment by lsw5835** [comment]
1. 

> 1. I didn't notice the distortion in s-o-p pronunciation before, it's an interesting finding. Is it occurred in words like '**O**k', 'apple**S**', 'hel**P**', etc.? Maybe that's because these pronunciations are harder to model?
> 2. I don't quite understand what the second problem is, what does 'rather than target speaker data' mean?
> 
> Maybe provide extra knowledges like pitch to the model can solve these problems? So far the only distortion-related objective metric I know is WER/CER/PER.

1. Yes that error is generated from time to time.
2. That means if the pitch or pronunciation in the source wav is not in the target, distortion occurs.

While looking for other augmentation methods, I found that there is a 'stretch function in utils.py'. Have you ever tested horizontal augmentation?

**Comment by OlaWod** [comment]
it'll be harder to convert if the voice of source and target are very different.
i did not use horizontal augmentation because it does not change the speaker information of source wav.
btw i'd like to share some files: ↓

https://user-images.githubusercontent.com/32514635/217289027-4e29eaa8-503d-4d10-b8c1-18e555045698.mp4

https://user-images.githubusercontent.com/32514635/217289034-40cce731-256e-4db6-9a45-ecc123061c62.mp4

https://user-images.githubusercontent.com/32514635/217289042-ff3af75d-a902-4f62-8ac3-f09a075be419.mp4

https://user-images.githubusercontent.com/32514635/217289048-fea202e6-2696-487a-b61a-e258f028dfe5.mp4

i think, by applying different vertical sr rates in a wav, the augmentation can be stronger and help the disentanglement better.

**Comment by lsw5835** [comment]
Thanks very much for answering.
